'''
Python Basic(1)
1. Data Type
2. List, Tuple, Dictionary
'''

In [1]:
print("*** Data Type ***")
### Integer and float numbers
a=17
b=7
c=a/b
print("a={} type={}".format(a,type(a)))
print("b={} type={}".format(b,type(b)))
print("c={} type={}".format(c,type(c)))
print("\n")



*** Data Type ***
a=17 type=<class 'int'>
b=7 type=<class 'int'>
c=2.4285714285714284 type=<class 'float'>




In [2]:
format_test = '{}, {:d}, {:02d}, {:03d}, {:.2f}'.format(a,a,a,b,c)
print(format_test)
print("\n")



17, 17, 17, 007, 2.43




In [3]:
### String
d=str(c)
print("d={} type={}".format(c,type(d)))
print(len(d),d[0:4],d[-3:])
c+=c  ## c=c+c
print(c)
d+=d  ## d=d+d
print(d)
print(len(d))
print("\n")

d=2.4285714285714284 type=<class 'str'>
18 2.42 284
4.857142857142857
2.42857142857142842.4285714285714284
36




In [4]:
### Printing unicode
print("Unicode Test")
print("El Ni\u00F1o")
print("Delta: {}, epsilon: {}, degree: {}".format('\u0394','\u03B5','\u00B0'))
print("\n")



Unicode Test
El Niño
Delta: Δ, epsilon: ε, degree: °




In [5]:
### Boolean
boo1, boo2 = True, False
print("boo1={} type={}".format(boo1,type(boo1)))
print("Value of bools")
print(int(boo1),int(boo2))
print("True+False=",boo1+boo2)
print("True and False=",boo1 and boo2)
print("bool(-1)={}, bool(0)={}, bool(1)={}, bool(2)={}".format(bool(-1),bool(0),bool(1),bool(2)))
print("bool(-0.1)={}, bool(0.)={}, bool(0.1)={}".format(bool(-0.1),bool(0.),bool(0.1)))
print('\n')



boo1=True type=<class 'bool'>
Value of bools
1 0
True+False= 1
True and False= False
bool(-1)=True, bool(0)=False, bool(1)=True, bool(2)=True
bool(-0.1)=True, bool(0.)=False, bool(0.1)=True




In [6]:
###---- List
print("*** List ***")
e=[a,b,c]
print("e={} type={}".format(e,type(e)))
print("e+e={}".format(e+e))
print("\n This is not a copy")
e2=e
e2[0]=5
print(e)
e3=e[:]
e3[0]=4
print(e)
print(e3)

*** List ***
e=[17, 7, 4.857142857142857] type=<class 'list'>
e+e=[17, 7, 4.857142857142857, 17, 7, 4.857142857142857]

 This is not a copy
[5, 7, 4.857142857142857]
[5, 7, 4.857142857142857]
[4, 7, 4.857142857142857]


In [7]:
###---- List
print("*** List ***")
e=[a,b,c]
print("e={} type={}".format(e,type(e)))
print("e+e={}".format(e+e))
print("\n This is not a copy")
e2=e
e2[0]=5
print(e)
e3=e[:]
e3[0]=4
print(e)
print(e3)

*** List ***
e=[17, 7, 4.857142857142857] type=<class 'list'>
e+e=[17, 7, 4.857142857142857, 17, 7, 4.857142857142857]

 This is not a copy
[5, 7, 4.857142857142857]
[5, 7, 4.857142857142857]
[4, 7, 4.857142857142857]


In [8]:
# e.sort()   ### This causes an error because strs and numbers are mixed in
f=e[:5]
f.sort()
print(f,sorted(e[:5]))
print("* min, max, sum")
print(min(e[:5]),max(e[:5]),sum(e[:5]))
print("\n")

print("* Slicing")
print(e)
print(e[::2]) ### = e[0:len(e):2]
print(e[::-1])
print("\n")

print("* Map(func, iter)")
aa=['abc','def','ghi']
bb=list(map(list,aa))
print(aa)
print("list(map(list,aa))=",bb)
print(list(aa[0]))
cc=list(range(5))
dd=list(map(float,cc))
print(cc)
print("list(map(float,cc))",dd)

[4.857142857142857, 5, 7] [4.857142857142857, 5, 7]
* min, max, sum
4.857142857142857 7 16.857142857142858


* Slicing
[5, 7, 4.857142857142857]
[5, 4.857142857142857]
[4.857142857142857, 7, 5]


* Map(func, iter)
['abc', 'def', 'ghi']
list(map(list,aa))= [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]
['a', 'b', 'c']
[0, 1, 2, 3, 4]
list(map(float,cc)) [0.0, 1.0, 2.0, 3.0, 4.0]


In [9]:
###--- Tuple
g=(1,2,3)
print("\ng={} type={}".format(g,type(g)))
# g[0]=10 ### This causes an error because Tuple prohibits assignment 
# g.append(4) ### Of course, no modification




g=(1, 2, 3) type=<class 'tuple'>


In [10]:
###--- Dictionary
h = {"brand": "Ford", "model": "Mustang", "year": 1964 }
print("h={} type={}".format(h,type(h)))
print(h["year"])  ### Access value by key

h={'brand': 'Ford', 'model': 'Mustang', 'year': 1964} type=<class 'dict'>
1964


'''
Python Basic(2)
3. IF
4. FOR
5. WHILE
'''


In [11]:
### If basic
if True:
   print("IF True\n")
elif False:
   print("Not printing here")
else:
   print("Not printing here")



IF True



In [12]:
### For basic
list1, list2, list3 = [], [], []
for i in range(20):
### range(20) = range(0,20) = range(0,20,1)
   if i%3==0:
      list1.append(i)
   elif i%3==1:
      list2.append(i)
   else:
      list3.append(i)

print(list1)
print(list2)
print(list3, '\n')



[0, 3, 6, 9, 12, 15, 18]
[1, 4, 7, 10, 13, 16, 19]
[2, 5, 8, 11, 14, 17] 



In [13]:
### For + zip
list4=[]
for i,j in zip(list1,list2):
   list4.append(str(i)+str(j))
#print(list4)
for a in list4:
   print(a)

print('\n')
list5=[]
for i,j,k in zip(list1,list2,list3):
   list5.append(str(i)+str(j)+str(k))
#print(list5)


01
34
67
910
1213
1516
1819




In [14]:
### For + enumerate
for i,a in enumerate(list5):
   print(i,a)



0 012
1 345
2 678
3 91011
4 121314
5 151617


In [15]:
### While
print('\n')
i=0
while i<len(list5):
   print(int(list5[i])-i)
   i+=1

print('\n')





12
344
676
91008
121310
151612




In [17]:
### Functions
def test_function():
   #Some contents
   return "Yes"

print(test_function(),'\n')

Yes 



In [18]:
###---

def sum_every2(num):
   '''
   Simple Function Example
   Argument "num" should be >0
   '''
   if num<=0:
      print("Input should be >0")
      return -999

   sum1=0
   for i in range(0,num,2):
      sum1+=i

   return sum1

print(sum_every2.__doc__)
print(sum_every2(10))
print(sum_every2(100))
print(sum_every2(-1),'\n')




   Simple Function Example
   Argument "num" should be >0
   
20
2450
Input should be >0
-999 



In [19]:
###---
print("Function: Simple version (lambda)")
sum_ev2 = lambda num: sum(list(range(0,num,2))) if num>0 else -999
print(sum_ev2(10))
print(sum_ev2(100))
print(sum_ev2(-1),'\n')


print("Function with default value(s)")
def sum_every_n(num,n=2):
   '''
   Simple Function Example with default argument
   Arg "num" should be >0
   Arg "n" default value is 2
   '''
   if num<=0:
      print("Input should be >0")
      return -999

   sum1=0
   for i in range(0,num,n):
      sum1+=i

   return sum1

print(sum_every_n.__doc__)
print(sum_every_n(10))
print(sum_every_n(100,3))
print(sum_every_n(100,n=3))
print(sum_every_n(num=100,n=3))
print(sum_every_n(-1),'\n')



Function: Simple version (lambda)
20
2450
-999 

Function with default value(s)

   Simple Function Example with default argument
   Arg "num" should be >0
   Arg "n" default value is 2
   
20
1683
1683
1683
Input should be >0
-999 



In [20]:
###---
from math import ceil
def lon_deg2x(lon,lon0,dlon):
    x=ceil((lon-lon0)/dlon)
    if lon0<0 and lon>180:
        x-= int(360/dlon)
    if lon0>0 and lon<0:
        x+= int(360/dlon)

    return x
lat_deg2y = lambda lat,lat0,dlat: ceil((lat-lat0)/dlat)

lon0=-179.5; dlon=1.
lat0=-89.5; dlat=1.
print("(0E,0N)=",lon_deg2x(0,lon0,dlon),lat_deg2y(0,lat0,dlat))



(0E,0N)= 180 90


A03.file_name_change.py3.py

In [24]:
import glob
from subprocess import call

indir='./data/'
fnames=glob.glob(indir+'*.*')

#modified by me start
#print(fnames)
#modified by me end

# At present, there is no file with ":" in its file name so nothing will happen. 
for fn in fnames:
    if ":" in fn:
        print(fn)
        fn2=fn.replace(":","-")

        print("Changed: "+fn2)
        call(["mv",fn,fn2])

In [27]:
import sys
import numpy as np
import os.path

from subprocess import call
#from pyhdf.SD import SD, SDC
import h5py
from netCDF4 import Dataset

import matplotlib.colors as cls
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator, FixedLocator, MultipleLocator

#import cartopy.crs as ccrs
#from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER

from sklearn import linear_model

from scipy.stats import kde

In [28]:
print("Sucess if no errors!")

Sucess if no errors!


"""
Numpy - basic methods
"""

In [29]:
import numpy as np

def show_array_info(a,show_contents=True):
   """ 
   Print information of numpy array
   """
   result="N_Dims={}, Shape={}, Data_Type={}".format(a.ndim, a.shape, a.dtype)
   print(result)
   if show_contents:
      print(a)
   return



In [30]:
### Make new array
zeros = np.zeros([3,4])
ones = np.ones([3,4],dtype=int)
empty = np.empty([3,4],dtype=np.float32)
full = np.full_like(zeros,-999.9)
print('\nnp.zeros') ;show_array_info(zeros)
print('\nnp.ones')  ;show_array_info(ones)
print('\nnp.empty') ;show_array_info(empty)
print('\nnp.full') ;show_array_info(full)

a=[[0,1,2,3],[4,5,6,7],[8,9,10,11]]  ### A list
b=np.array(a)
c=np.asarray(a)
d=np.asfarray(a)

print('\nnp.array') ;show_array_info(b)
print('\nnp.asarray')  ;show_array_info(c,show_contents=False)
print('\nnp.asfarray') ;show_array_info(d,show_contents=False)




np.zeros
N_Dims=2, Shape=(3, 4), Data_Type=float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

np.empty
N_Dims=2, Shape=(3, 4), Data_Type=float32
[[-3.1484815e-05  1.5304982e-41 -3.1484960e-05  1.5304982e-41]
 [ 2.3822074e-44  1.5304982e-41  2.3267113e+13  3.0611365e-41]
 [-1.9942292e-10  1.5304982e-41  2.8025969e-45  2.7952212e+20]]

np.full
N_Dims=2, Shape=(3, 4), Data_Type=float64
[[-999.9 -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 -999.9]]

np.array
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

np.asarray
N_Dims=2, Shape=(3, 4), Data_Type=int64

np.asfarray
N_Dims=2, Shape=(3, 4), Data_Type=float64


In [31]:
e=np.arange(12)  ### Similar to range()
print('\nnp.arange(12)',e.shape)
e=np.reshape(e,[4,3])   ### Reshape: Very Important!
print('\n After Reshape')
show_array_info(e)
e=e.T  ### Same: transpose()
print('\n After Transpose')
show_array_info(e)
# e=np.arange(12).reshape([4,3])

f=np.linspace(1,10,4)
print('\n np.linspace(1,10,4)'); show_array_info(f)




np.arange(12) (12,)

 After Reshape
N_Dims=2, Shape=(4, 3), Data_Type=int64
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 After Transpose
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

 np.linspace(1,10,4)
N_Dims=1, Shape=(4,), Data_Type=float64
[ 1.  4.  7. 10.]


In [32]:
### Simple operation
print('\n Adding Array')
tmp_plus= ones+ones
show_array_info(tmp_plus)

print('\n Adding Int Array and Float Array')
tmp_plus2= ones+full
show_array_info(tmp_plus2)

print('\n Array*Array')
tmp_multiply= tmp_plus*tmp_plus
show_array_info(tmp_multiply)

print('\n Array*number')
tmp_multiply2= tmp_multiply*3
show_array_info(tmp_multiply2)

print('\n Array_2D*Array_1D')
tmp_multiply3= tmp_multiply*f[None,:]
show_array_info(tmp_multiply3)





 Adding Array
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]

 Adding Int Array and Float Array
N_Dims=2, Shape=(3, 4), Data_Type=float64
[[-998.9 -998.9 -998.9 -998.9]
 [-998.9 -998.9 -998.9 -998.9]
 [-998.9 -998.9 -998.9 -998.9]]

 Array*Array
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]

 Array*number
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]

 Array_2D*Array_1D
N_Dims=2, Shape=(3, 4), Data_Type=float64
[[ 4. 16. 28. 40.]
 [ 4. 16. 28. 40.]
 [ 4. 16. 28. 40.]]


In [33]:
### Copy or not copy
ones2=ones
ones2[0,0]=2
print('\n Copy or not?')
show_array_info(ones)

ones3=np.copy(ones)
ones3[0,0]=3
print('\n Copy or not?')
show_array_info(ones)

ones4=ones[:]
ones4[0,0]=4
print('\n Copy or not?')
show_array_info(ones)




 Copy or not?
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[2 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

 Copy or not?
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[2 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

 Copy or not?
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[4 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [34]:
### Transform the array
print('\n Starting Array before Transformation')
show_array_info(e)

print('\n Array.astype(np.int16)')
e2=e.astype(np.int16)
show_array_info(e2,show_contents=False)

print('\n Partial sum of array')
show_array_info(e2.reshape([3,2,2]).sum(axis=2))

print('\n Swap Axes')
e2=e2.reshape([-1,2,2]).swapaxes(1,2).reshape([-1,4]) ### "-1" in reshape means "all others"
show_array_info(e2)

print('\n Slicing with index list [:,[1,3]]')
index_list=[1,3]
e3=e2[:,index_list]
show_array_info(e3)




 Starting Array before Transformation
N_Dims=2, Shape=(3, 4), Data_Type=int64
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

 Array.astype(np.int16)
N_Dims=2, Shape=(3, 4), Data_Type=int16

 Partial sum of array
N_Dims=2, Shape=(3, 2), Data_Type=int64
[[ 3 15]
 [ 5 17]
 [ 7 19]]

 Swap Axes
N_Dims=2, Shape=(3, 4), Data_Type=int16
[[ 0  6  3  9]
 [ 1  7  4 10]
 [ 2  8  5 11]]

 Slicing with index list [:,[1,3]]
N_Dims=2, Shape=(3, 2), Data_Type=int16
[[ 6  9]
 [ 7 10]
 [ 8 11]]


In [35]:
### Indexing
print('\n Find location satisfying specific condition')
loc=np.where(np.logical_and(e2>5,e2<10))
print(type(loc),len(loc))
for j,i in zip(*loc):
  print("j={}, i={}, value={}".format(j,i,e2[j,i]))

print('\n Usually don\'t need to know the location')
idx=np.logical_and(e2>5,e2<10)
show_array_info(idx)
show_array_info(e2[idx])


 Find location satisfying specific condition
<class 'tuple'> 2
j=0, i=1, value=6
j=0, i=3, value=9
j=1, i=1, value=7
j=2, i=1, value=8

 Usually don't need to know the location
N_Dims=2, Shape=(3, 4), Data_Type=bool
[[False  True False  True]
 [False  True False False]
 [False  True False False]]
N_Dims=1, Shape=(4,), Data_Type=int16
[6 9 7 8]


'''
### Logical operation
np.logical_and()
np.logical_or()
np.logical_not()

### Expanding Array
repeat()
np.tile()
np.concatenate()
np.hstack()
np.vstack()

### Simple statistical methods
dot()
max()
mean(); np.average()
min()
sum()
std()
var()
np.median()
np.around()
sort()
np.cumsum()
np.percentile()
np.digitize()
np.histogram()
np.corrcoef()

### Argument methods
argmax() # Return index of maximum value
argmin()
argsort()

### Mathematical functions
np.sin()
np.cos()
np.around()
np.floor()
np.ceil()
np.power()
np.log()
np.exp()

### Checking data
np.isnan()
np.isinf()
np.isfinite()

### Treat NaN values
np.nan_to_num()
np.nansum()

### https://docs.scipy.org/doc/numpy/reference/



'''


B02.binary_read_write+RMS_of_MonthlyData.py3.py

In [36]:
import sys
import numpy as np
import os.path

In [37]:
def bin_file_read2mtx(fname,dtype=np.float32):
    """ Open a binary file, and read data 
        fname : file name
        dtype   : data type; np.float32 or np.float64, etc. """

    if not os.path.isfile(fname):
        #print( "File does not exist:"+fname); sys.exit()
        sys.exit("File does not exist:"+fname)

    #fd=open(fname,'rb')
    with open(fname,'rb') as f:
        bin_mat = np.fromfile(file=f,dtype=dtype)
    #fd.close() ### Not needed with "with"

    return bin_mat

from math import ceil
def lon_deg2x(lon,lon0,dlon):
    x=ceil((lon-lon0)/dlon)
    if lon0<0 and lon>180:
        x-= int(360/dlon)
    if lon0>0 and lon<0:
        x+= int(360/dlon)

    return x


In [38]:
lat_deg2y = lambda lat,lat0,dlat: ceil((lat-lat0)/dlat)

In [39]:
###---- Main

##-- Parameters
indir='./data/'
fname=indir+'HadISST1.sample.348x180x360.f32dat'

nt=348 ### Monthly for 29 years
nlon=360; lon0=0.5; dlon=1.
nlat=180; lat0=-89.5; dlat=1.

undef= -9999.

##-- Read binary file
sst=bin_file_read2mtx(fname)  ### "dtype=np.float32" is omitted. 
sst=sst.reshape([nt,nlat,nlon])
print(sst.shape)



(348, 180, 360)


In [40]:
##-- Sampling for limited regiosn (60E-160E,25S-25N)
lon_deg_range=[60,160]
lat_deg_range=[-25,25]

lon_idx=[lon_deg2x(x,lon0,dlon) for x in lon_deg_range]; nlon2=lon_idx[1]-lon_idx[0]
lat_idx=[lat_deg2y(y,lat0,dlat) for y in lat_deg_range]; nlat2=lat_idx[1]-lat_idx[0]
print(lon_idx, lat_idx)
sst=sst[:,lat_idx[0]:lat_idx[1],lon_idx[0]:lon_idx[1]]
print(sst.shape)



[60, 160] [65, 115]
(348, 50, 100)


In [41]:
##-- Identify missings
msidx= sst<-100
msidx=msidx.sum(axis=0).astype(bool) ### For identify gridcells having any missings for all time
print(msidx.shape,msidx.sum())



(50, 100) 799


In [42]:
##-- Remove annual cycle
#- 1. Calc annual cycle
anncyl= sst.reshape([-1,12,nlat2,nlon2]).mean(axis=0)
print(anncyl.shape)



(12, 50, 100)


In [43]:
#- 2. Calc anomalies
sstano= sst.reshape([-1,12,nlat2,nlon2])-anncyl[None,:,:,:]
sstano= sstano.reshape([nt,nlat2,nlon2])

##-- Calc Root-Mean-Squared-Sum of anomalies
rms= np.sqrt(np.mean(sstano*sstano,axis=0))
print(rms[~msidx].max(), rms[~msidx].min())



0.71170914 0.1314251


In [44]:
##-- Restore missings
rms[msidx]=undef



In [54]:
##-- Write to binary file
outdir=indir
outfn=outdir+'HadSST_rms.{}x{}.f32dat'.format(nlat2,nlon2)

##-- Protect existing file
if os.path.isfile(outfn):
    sys.exit("Already Exist: "+outfn)
else:
    with open(outfn, 'wb') as f:
        rms.astype(np.float32).tofile(f)



C01.Text_read_write+Regression+Density.py3.py

In [46]:
import sys
import numpy as np
import os.path



In [47]:
###---- Main

##-- Parameters
indir='./data/'
fname=indir+'storm_track.txt'

data=[]; time_info=[]
with open(fname,'r') as f:
    for i,line in enumerate(f):
        words=line.strip().split()
        #print(i,words)

        if i>0:  ### Exclude header
            flos=list(map(float,words[:4]))
            ints=list(map(int,words[4:]))

            data.append(flos)
            time_info.append(ints)



data=np.asarray(data)
time_info=np.asarray(time_info)

print(data.shape, time_info.shape)

###-------------


(17, 4) (17, 4)


In [48]:
###--- Linear Regression
from sklearn import linear_model


## For linear-regression
regr=linear_model.LinearRegression()   ### Initiate Regression Object

xdata=data[:,2].reshape([-1,1])  ## wind speed
ydata=data[:,3].reshape([-1,1])  ## surface pressure

regr.fit(xdata,ydata)
r2score=regr.score(xdata,ydata)
print(u"Coeff.={:.2f}, Intercept={:.2f}, R\u00B2 Score={:.3f}".format(regr.coef_[0][0], regr.intercept_[0],r2score))

#y_pred=regr.predict(xcoord)
regr.__init__()     ### Re-initiate in order to use next time with different data


###-------------

Coeff.=-1.41, Intercept=1023.97, R² Score=0.707


In [49]:
### Calculate density of data
from scipy.stats import kde

xdata=data[:,2]  ## wind speed
ydata=data[:,3]  ## surface pressure
k=kde.gaussian_kde([xdata,ydata])
xi,yi=np.mgrid[xdata.min():xdata.max():100j,ydata.min():ydata.max():100j]
zi=k(np.vstack([xi.flatten(),yi.flatten()]))

print(zi.shape, zi.argmax())

j,i=np.unravel_index(zi.argmax(),xi.shape)
xloc= xdata.min()+(xdata.max()-xdata.min())/100*i
yloc= ydata.min()+(ydata.max()-ydata.min())/100*j
print("Max Density is {:.05f} when wind speed={:.2f} and pressure={:.2f}".format(zi.max(),xloc,yloc))


###-------------


(10000,) 4929
Max Density is 0.00442 when wind speed=26.24 and pressure=983.44


In [55]:
### Write to text file

outdir = indir
outfn = outdir+'text_write_ex1.txt'

##-- Protect existing file
if os.path.isfile(outfn):
    sys.exit("Already Exist: "+outfn)
else:
    with open(outfn,'w') as f:
        header="Longitude, Wind, Year, Month"
        f.write(header+"\n")
        
        #modified by me start
        print(data.shape[0])
        #modified by me end

        for i in range(data.shape[0]):
            data_txt="{:.2f}, {:.2f}, {:d}, {:02d}".format(data[i,0],data[i,2],time_info[i,0],time_info[i,1])
            f.write(data_txt+"\n")



17


C02a.HDF4_file_header_info.py3.py

In [56]:
"""
Print header information of HDF4 file


"""


import sys
import numpy as np
import os.path

from subprocess import call
from pyhdf.SD import SD, SDC


ModuleNotFoundError: No module named 'pyhdf'

In [57]:
def open_hdf4(fname):
    if not os.path.isfile(fname):
        print("File does not exist:"+fname)
        sys.exit()

    hid=SD(fname,SDC.READ)
    print("Open:",fname)
    return hid



In [58]:
##-- Parameters
indir='./data/'
fname=indir+'3B42.20180218.00.7.HDF'

hdf_f = open_hdf4(fname)

dinfo= hdf_f.datasets()
#print(hdf_f.datasets())
for dd in dinfo:
    print("Name: {}".format(dd))
    print("   Values: {}".format(dinfo[dd]))



NameError: name 'SD' is not defined

In [59]:
'''
h5keys=[]
hdf_f.visit(h5keys.append)


it=13
print("\n{}".format(h5keys[it]))
dset=hdf_f[h5keys[it]]
for (name, val) in dset.attrs.items():
    print("Name: {}".format(name))
    print("   Values: {}".format(val))

'''


'\nh5keys=[]\nhdf_f.visit(h5keys.append)\n\n\nit=13\nprint("\n{}".format(h5keys[it]))\ndset=hdf_f[h5keys[it]]\nfor (name, val) in dset.attrs.items():\n    print("Name: {}".format(name))\n    print("   Values: {}".format(val))\n\n'

C02b.HDF5_file_header_info.py3.py

In [60]:
"""
Print header information of HDF5 file

"""


import sys
import numpy as np
import os.path


import h5py

In [61]:
def open_hdf5(fname):
    if not os.path.isfile(fname):
        print("File does not exist:"+fname)
        sys.exit()

    hid=h5py.File(fname,'r')
    print("Open:",fname)
    return hid

def printname(name):
    global i
    print(i,name)
    i+=1

In [62]:
##-- Parameters
indir='./data/'
#fname=indir+'3B-HHR.MS.MRG.3IMERG.20180218-S000000-E002959.0000.V06A.HDF5'
fname=indir+'AERDB_L2_VIIRS_SNPP.A2014067.1936.001.2019056041229.nc'
#fname=indir+'AERDB_temp.hdf5'

hdf_f = open_hdf5(fname)

i=0
hdf_f.visit(printname)


h5keys=[]
hdf_f.visit(h5keys.append)



Open: ./data/AERDB_L2_VIIRS_SNPP.A2014067.1936.001.2019056041229.nc
0 Aerosol_Optical_Thickness_550_Land
1 Aerosol_Optical_Thickness_550_Land_Best_Estimate
2 Aerosol_Optical_Thickness_550_Land_Ocean
3 Aerosol_Optical_Thickness_550_Land_Ocean_Best_Estimate
4 Aerosol_Optical_Thickness_550_Ocean
5 Aerosol_Optical_Thickness_550_Ocean_Best_Estimate
6 Aerosol_Optical_Thickness_550_STDV_Land
7 Aerosol_Optical_Thickness_550_STDV_Ocean
8 Aerosol_Optical_Thickness_QA_Flag_Land
9 Aerosol_Optical_Thickness_QA_Flag_Ocean
10 Aerosol_Type_Land
11 Aerosol_Type_Land_Ocean
12 Aerosol_Type_Ocean
13 Algorithm_Flag_Land
14 Algorithm_Flag_Land_for_test
15 Algorithm_Flag_Ocean
16 Angstrom_Exponent_Land
17 Angstrom_Exponent_Land_Best_Estimate
18 Angstrom_Exponent_Land_Ocean
19 Angstrom_Exponent_Land_Ocean_Best_Estimate
20 Angstrom_Exponent_Ocean
21 Angstrom_Exponent_Ocean_Best_Estimate
22 Cell_Average_Chl
23 Cell_Average_Elevation_Land
24 Cell_Average_Elevation_Ocean
25 Fine_Mode_Fraction_550_Ocean
26 Fine_Mo

In [63]:
it=2
print("\n{}".format(h5keys[it]))
dset=hdf_f[h5keys[it]]
for (name, val) in dset.attrs.items():
    print("Name: {}".format(name))
    print("   Values: {}".format(val))




Aerosol_Optical_Thickness_550_Land_Ocean
Name: units
   Values: b'1'
Name: valid_range
   Values: [0. 5.]
Name: long_name
   Values: b'Deep Blue/SOAR aerosol optical thickness at 550 nm over land and ocean'
Name: coordinates
   Values: b'Longitude Latitude'
Name: _FillValue
   Values: [-999.]
Name: DIMENSION_LIST
   Values: [array([<HDF5 object reference>], dtype=object)
 array([<HDF5 object reference>], dtype=object)]


In [64]:
it=43
print("\n{}".format(h5keys[it]))
dset=hdf_f[h5keys[it]]
for (name, val) in dset.attrs.items():
    print("Name: {}".format(name))
    print("   Values: {}".format(val))


Spectral_Aerosol_Optical_Thickness_Land
Name: long_name
   Values: b'Deep Blue spectral aerosol optical thickness at 412, 488, and 670 nm over land'
Name: units
   Values: b'1'
Name: coordinates
   Values: b'Longitude Latitude'
Name: _FillValue
   Values: [-999.]
Name: valid_range
   Values: [0. 5.]
Name: DIMENSION_LIST
   Values: [array([<HDF5 object reference>], dtype=object)
 array([<HDF5 object reference>], dtype=object)
 array([<HDF5 object reference>], dtype=object)]


C02c.HDF5_read_write.py3.py

In [65]:
"""
Read HDF5 file and write a few variables to a new hdf5 file

"""


import sys
import numpy as np
import os.path


import h5py

In [66]:
def open_hdf5(fname):
    if not os.path.isfile(fname):
        print("File does not exist:"+fname)
        sys.exit()

    hid=h5py.File(fname,'r')
    print("Open:",fname)
    return hid


def hdf_key_test(f,key1):
    if key1 not in list(f.keys()):
        print(list(f.keys()))
        sys.exit('Key name is not matched: {}'.format(key1))
    else:
        print('key is available')



In [67]:
##-- Parameters
indir='./data/'
#fname=indir+'3B-HHR.MS.MRG.3IMERG.20180218-S000000-E002959.0000.V06A.HDF5'
fname=indir+'AERDB_L2_VIIRS_SNPP.A2014067.1936.001.2019056041229.nc'

h5keys=['Longitude','Latitude','Aerosol_Optical_Thickness_550_Land_Ocean','Spectral_Aerosol_Optical_Thickness_Land']

undef = -999.

In [68]:
## Open file and test keys
hdf_f = open_hdf5(fname)
for key in h5keys:
    hdf_key_test(hdf_f,key)



Open: ./data/AERDB_L2_VIIRS_SNPP.A2014067.1936.001.2019056041229.nc
key is available
key is available
key is available
key is available


In [69]:
## Read data
lons=hdf_f[h5keys[0]]  ## h5py data array
lats=hdf_f[h5keys[1]][:]  ## Now numpy array
aot550lo=hdf_f[h5keys[2]][:]
saotl=hdf_f[h5keys[3]][:]

print(type(lons),type(lats))
print(lons.shape,lats.shape,aot550lo.shape,saotl.shape)



<class 'h5py._hl.dataset.Dataset'> <class 'numpy.ndarray'>
(404, 400) (404, 400) (404, 400) (3, 404, 400)


In [70]:
lons=lons[:]
hdf_f.close()

udidx= aot550lo==undef
print("Missing rate of {} = {:.2f}%".format(h5keys[2],udidx.sum()/aot550lo.reshape(-1).shape[0]*100.))



Missing rate of Aerosol_Optical_Thickness_550_Land_Ocean = 68.18%


In [71]:
for k in range(saotl.shape[0]):
    idx= saotl[k,:,:]==undef

    iidx= np.logical_and(idx,udidx)
    print(idx.sum(),udidx.sum(),iidx.sum())

    saotl[k,~iidx]=undef


115376 110172 109938
115376 110172 109938
115376 110172 109938


In [72]:
### Write
outdir = indir
outfn = outdir+'AERDB_temp.hdf5'
with h5py.File(outfn, 'w') as f:
    dset1 = f.create_dataset("lon",data=lons)
    dset2 = f.create_dataset("lat",data=lats)
    dset3 = f.create_dataset("Screened_"+h5keys[3], data=saotl, dtype='f4')

    f["lon"].dims[0].label='lon'
    f["lon"].dims[1].label='lat'

    f["lat"].dims[0].label='lon'
    f["lat"].dims[1].label='lat'

    f["Screened_"+h5keys[3]].dims[0].label='bands(412, 488, 670)'
    f["Screened_"+h5keys[3]].dims[1].label='lon'
#    f["Screened_"+h5keys[3]].dims[2].label='lat'
    dset3.dims[2].label='lat'
    dset3.attrs['_FillValue']=undef



C03a.NetCDF_file_header_info.py3.py

In [73]:
"""
Print header information of NetCDF file

Both NetCDF3 and NetCDF4 formats are supported.

"""


import sys
import numpy as np
import os.path

from subprocess import call
from netCDF4 import Dataset

In [74]:
def open_netcdf(fname):
    if not os.path.isfile(fname):
        print("File does not exist:"+fname)
        sys.exit()

    fid=Dataset(fname,'r')
    print("Open:",fname)
    return fid



In [87]:
##-- Parameters
indir='./data/'
#fname=indir+'AERDB_L2_VIIRS_SNPP.A2014067.1936.001.2019056041229.nc'
#fname=indir+'AERDB_L2_VIIRS_SNPP.A2014067.1936.001.2019056041229.nc'  #HDF?
#File name changed!
#fname=indir+'slp_wrfout_d01_2018-02-20_00:00:00.nc'
fname=indir+'slp_wrfout_d01_2018-02-20_00-00-00.nc'

### Get file name from argument
#if len(sys.argv)<2:
#    sys.exit("Please provide NC file name as an argument!")
#else:
#    fname= str(sys.argv[1])   ## [1]: the first argument

In [88]:



nc_f= open_netcdf(fname)
print("\n*** NC Format=",nc_f.data_model)

###--- Attributes
print("\n*** Global Attributes ***")
nc_attrs= nc_f.ncattrs()
for nc_attr in nc_attrs:
    print('   {}: {}'.format(nc_attr,nc_f.getncattr(nc_attr)))

print("\n*** Dimensions ***")
for nc_dim in nc_f.dimensions:
#    print('   Name: {}'.format(nc_dim))
    print('   {}'.format(str(nc_f.dimensions[nc_dim]).split(':')[1]))

print("\n*** Variables ***")
for var in nc_f.variables:
    print(nc_f.variables[var])

nc_f.close()




Open: ./data/slp_wrfout_d01_2018-02-20_00-00-00.nc

*** NC Format= NETCDF3_CLASSIC

*** Global Attributes ***

*** Dimensions ***
    name = 'Time', size = 1

    name = 'south_north', size = 1200

    name = 'west_east', size = 1200


*** Variables ***
<class 'netCDF4._netCDF4.Variable'>
float32 SLP(Time, south_north, west_east)
    FieldType: 104
    MemoryOrder: XYZ
    stagger: 
    coordinates: XLONG XLAT XTIME
    units: hPa
    description: Sea Level Pressure
unlimited dimensions: 
current shape = (1, 1200, 1200)
filling on, default _FillValue of 9.969209968386869e+36 used

<class 'netCDF4._netCDF4.Variable'>
float32 XLAT(Time, south_north, west_east)
    coordinates: XLONG XLAT
    stagger: 
    units: degree_north
    description: LATITUDE, SOUTH IS NEGATIVE
    MemoryOrder: XY 
    FieldType: 104
unlimited dimensions: 
current shape = (1, 1200, 1200)
filling on, default _FillValue of 9.969209968386869e+36 used

<class 'netCDF4._netCDF4.Variable'>
float32 XLONG(Time, south_nor

C03b.NetCDF_read_write.py3.py

"""
### Read NC files of 4 variables, and write a NC file all together

Input files:
data/slp_wrfout_d01_2018-02-17_00-00-00.nc
data/hgt_1000hPa_wrfout_d01_2018-02-17_00-00-00.nc
data/hgt_500hPa_wrfout_d01_2018-02-17_00-00-00.nc
data/hgt_200hPa_wrfout_d01_2018-02-17_00-00-00.nc

###Every 6 hours for 3 days

"""


In [90]:
import sys
import numpy as np
import os.path
from subprocess import call
from datetime import timedelta, date, datetime
from netCDF4 import Dataset, date2num

In [91]:
def open_netcdf(fname):
    if not os.path.isfile(fname):
        print("File does not exist:"+fname)
        sys.exit()

    fid=Dataset(fname,'r')
    print("Open:",fname)
    return fid


def daterange(start_date, end_date):
    ### Including end date
    for n in range(int((end_date - start_date).days)+1):
        yield start_date + timedelta(n)



In [92]:
###--- Parameters
start_date = date(2018,2,17)  ### Start Date
end_date = date(2018,2,20)   ### Including this End Date

vars = ['slp','hgt_1000hPa','hgt_500hPa','hgt_200hPa']
dim_names = ['XLAT','XLONG']
indir = './data/'
outdir = indir



In [93]:
for oneday in daterange(start_date,end_date):
    dd=oneday.strftime('%Y-%m-%d')

    file_test=False
    f_ids=[]
    for tt in range(0,24,6):
        f_ids.append([])
        for vv in vars:
            infn=indir+'{}_wrfout_d01_{}_{:02d}-00-00.nc'.format(vv,dd,tt)
            #nc_f=open_netcdf(infn)
            if not os.path.isfile(infn):
                print(infn+" not available")
                file_test=True
                break
            else:
                fid=Dataset(infn,'r')
                f_ids[-1].append(fid)


    if file_test:
        sys.exit("Files are incomplete on {}".format(dd))
    else:
        f_id_tmp= f_ids[0][0]
        dims = f_id_tmp.variables[vars[0].upper()].dimensions
        lats = f_id_tmp.variables['XLAT'][:]
        if lats.shape[0]==1:
            lats=lats.reshape(lats.shape[1:])
        lons = f_id_tmp.variables['XLONG'][:]
        if lons.shape[0]==1:
            lons=lons.reshape(lons.shape[1:])
        print(dims,type(lons),lons.shape)


        times = [datetime(oneday.year,oneday.month,oneday.day)+n*timedelta(hours=6) for n in range(len(f_ids))]
        print(times)

        data=[]
        for fids in f_ids:
            for i,fid in enumerate(fids):
                vname=vars[i].split('_')[0].upper()
                if i==0:
                    temp=fid.variables[vname][:]
                else:
                    temp=np.concatenate((temp,fid.variables[vname][:]))

            print(vars[i],temp.shape)
            data.append(temp)

        data=np.asarray(data).astype(np.float32)
        print(data.shape)



        ### Ready to Create a daily NC file
        outfn=outdir+'wrfout_d01_{}.nc'.format(dd)
        ncfw= Dataset(outfn, "w", format="NETCDF4")

        ## Dimensions
        ln=ncfw.createDimension('lon',lons.shape[0])
        lt=ncfw.createDimension('lat',lats.shape[1])
        lv=ncfw.createDimension('lev',3)
        tm=ncfw.createDimension('time',len(times))

        lonsnc = ncfw.createVariable('lon','f4',('lon','lat',))
        latsnc = ncfw.createVariable('lat','f4',('lat','lat',))
        levsnc = ncfw.createVariable('lev','f4',('lev',))
        timenc = ncfw.createVariable('time','f8',('time',))

        lonsnc[:]=lons; latsnc[:]=lats
        lonsnc.units = 'degrees_east'; latsnc.units = 'degrees_north'
        levsnc[:]=[1000,500,200]
        levsnc.units = 'hPa'

        timenc.units = 'hours since 0001-01-01 00:00:00.0'
        timenc.calendar = 'gregorian'
        timenc[:] = date2num(times, timenc.units, calendar=timenc.calendar)

        ## Data variables
        slpnc = ncfw.createVariable('SLP','f4',('time','lat','lon'))
        slpnc[:] = data[:,0,:,:]
        hgtnc = ncfw.createVariable('HGT','f4',('time','lev','lat','lon'))
        hgtnc[:] = data[:,1:,:,:]

        ## Attributions
        ncfw.description = 'Model output on {}'.format(dd)

        ## Close file
        print("{} is written.".format(outfn))
        ncfw.close()




('Time', 'south_north', 'west_east') <class 'numpy.ma.core.MaskedArray'> (1200, 1200)
[datetime.datetime(2018, 2, 17, 0, 0), datetime.datetime(2018, 2, 17, 6, 0), datetime.datetime(2018, 2, 17, 12, 0), datetime.datetime(2018, 2, 17, 18, 0)]
hgt_200hPa (4, 1200, 1200)
hgt_200hPa (4, 1200, 1200)
hgt_200hPa (4, 1200, 1200)
hgt_200hPa (4, 1200, 1200)
(4, 4, 1200, 1200)
./data/wrfout_d01_2018-02-17.nc is written.
('Time', 'south_north', 'west_east') <class 'numpy.ma.core.MaskedArray'> (1200, 1200)
[datetime.datetime(2018, 2, 18, 0, 0), datetime.datetime(2018, 2, 18, 6, 0), datetime.datetime(2018, 2, 18, 12, 0), datetime.datetime(2018, 2, 18, 18, 0)]
hgt_200hPa (4, 1200, 1200)
hgt_200hPa (4, 1200, 1200)
hgt_200hPa (4, 1200, 1200)
hgt_200hPa (4, 1200, 1200)
(4, 4, 1200, 1200)
./data/wrfout_d01_2018-02-18.nc is written.
('Time', 'south_north', 'west_east') <class 'numpy.ma.core.MaskedArray'> (1200, 1200)
[datetime.datetime(2018, 2, 19, 0, 0), datetime.datetime(2018, 2, 19, 6, 0), datetime.date

SystemExit: Files are incomplete on 2018-02-20

/discover/nobackup/jyoo8/miniconda2/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2969: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


sst_map+masked_array.py3.py

In [94]:
import sys
import numpy as np
import os.path
from subprocess import call



In [95]:
def bin_file_read2mtx(fname,dtype=np.float32):
    """ Open a binary file, and read data 
        fname : file name
        dtype   : data type; np.float32 or np.float64, etc. """

    if not os.path.isfile(fname):
        #print( "File does not exist:"+fname); sys.exit()
        sys.exit("File does not exist:"+fname)

    #fd=open(fname,'rb')
    with open(fname,'rb') as f:
        bin_mat = np.fromfile(file=f,dtype=dtype)
    #fd.close() ### Not needed with "with"

    return bin_mat

from math import ceil
def lon_deg2x(lon,lon0,dlon):
    x=ceil((lon-lon0)/dlon)
    if lon0<0 and lon>180:
        x-= int(360/dlon)
    if lon0>0 and lon<0:
        x+= int(360/dlon)

    return x
lat_deg2y = lambda lat,lat0,dlat: ceil((lat-lat0)/dlat)

def map_common(ax1,gl_loc=[True,True,False,True],gl_dlon=60,gl_dlat=30):
    ax1.set_title(subtit,x=0.,ha='left',fontsize=13,stretch='semi-condensed')
    ax1.coastlines(color='silver',linewidth=1.)

    gl = ax1.gridlines(crs=ccrs.PlateCarree(), draw_labels=True,
                       linewidth=0.6, color='gray', alpha=0.5, linestyle='--')

    gl.ylabels_left = gl_loc[0]
    gl.ylabels_right = gl_loc[1]
    gl.xlabels_top = gl_loc[2]
    gl.xlabels_bottom = gl_loc[3]

    gl.xlocator = FixedLocator(range(-180+gl_dlon,361,gl_dlon)) #[0,60,180,240,360]) #np.arange(-180,181,60))
    gl.ylocator = MultipleLocator(gl_dlat)
    gl.xformatter = LONGITUDE_FORMATTER
    gl.yformatter = LATITUDE_FORMATTER
    gl.xlabel_style = {'size': 11, 'color': 'k'}
    gl.ylabel_style = {'size': 11, 'color': 'k'}

def add_colorbar(cb_ax,cblab,horizontal=True):

    global clmin, clmax
    tt=np.arange(clmin,clmax+1,4)
    #tt2=[str(x)+'%' for x in tt]
    if horizontal:
        cb = fig.colorbar(cs,cax=cb_ax,orientation='horizontal',ticks=tt,extend='both')
        cb.ax.set_xticklabels(tt,size=11)
        cb.ax.set_xlabel(cblab)
    else:
        cb = fig.colorbar(cs,cax=cb_ax,orientation='vertical',ticks=tt,extend='both')
        cb.ax.set_yticklabels(tt,size=11)
        cb.ax.set_ylabel(cblab)



In [96]:
###---- Main

##-- Parameters
indir='./data/'
fname=indir+'HadISST1.sample.348x180x360.f32dat'

nt=348 ### Monthly for 29 years
nlon=360; lon0=0.5; dlon=1.
nlat=180; lat0=-89.5; dlat=1.

undef= -9999.

##-- Read binary file
sst=bin_file_read2mtx(fname)  ### "dtype=np.float32" is omitted. 
sst=sst.reshape([nt,nlat,nlon])
print(sst.shape)

###--------

(348, 180, 360)


In [97]:
##-- Identify missings
msidx= sst<-100
msidx=msidx.sum(axis=0).astype(bool) ### For identify gridcells having any missings for all time
print(msidx.shape,msidx.sum())

sstmean= sst.mean(axis=0)
sstmean[msidx]=undef
sm_max,sm_min=sstmean[~msidx].max(), sstmean[~msidx].min()
print("Min and Max of Mean SST=",sm_min, sm_max)

(180, 360) 33219
Min and Max of Mean SST= 1.4067242 29.744629


In [98]:
##-- Sampling for limited regiosn 
lon_deg_range=[-60,30]
lat_deg_range=[40,75]

lon_idx=[lon_deg2x(x,lon0,dlon) for x in lon_deg_range]; nlon2=lon_idx[1]-lon_idx[0]
lat_idx=[lat_deg2y(y,lat0,dlat) for y in lat_deg_range]; nlat2=lat_idx[1]-lat_idx[0]
print(lon_idx, lat_idx)
### In the case of trouble of lon_idx
### lon_idx[1] < lon_idx[0]
### Now need to make lon-list

lon_list=list(range(lon_idx[0],nlon,1))+list(range(lon_idx[1]))
sstmean2=sstmean[lat_idx[0]:lat_idx[1],lon_list]
print(sstmean2.shape)



[300, 30] [130, 165]
(35, 90)


In [99]:
### The other maskig method
sst_rg=sst[:,lat_idx[0]:lat_idx[1],lon_list]
sst_rg=np.ma.masked_less(sst_rg,-100)
print(type(sst_rg))
sstmean_ma=sst_rg.mean(axis=0)



<class 'numpy.ma.core.MaskedArray'>


In [100]:
###--- Map Plot
import matplotlib            ### Discover only
matplotlib.use('TkAgg')      ### Discover only
import matplotlib.colors as cls
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator, FixedLocator, MultipleLocator

import cartopy.crs as ccrs
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER



/discover/nobackup/jyoo8/miniconda2/envs/py36/lib/python3.6/site-packages/ipykernel/__main__.py:3: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/discover/nobackup/jyoo8/miniconda2/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/discover/nobackup/jyoo8/miniconda2/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/discover/nobackup/jyoo8/miniconda2/envs/py36/lib/python3.6/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/discover/nobackup/jyoo8/miniconda2/envs/py36/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    ap

ModuleNotFoundError: No module named 'cartopy'

In [101]:
fig=plt.figure()
fig.set_size_inches(8.5,8)  ## (xsize,ysize)
suptit="SST Map"
fig.suptitle(suptit,fontsize=17,y=0.98,stretch='semi-condensed') ## x=0., ha='left'

left,right,top,bottom=0.05,0.95,0.925,0.05
iix=left; gapx=0.02; npnx=2
lx=(right-iix-gapx*(npnx-1))/float(npnx)
iiy=top; gapy=0.12; npny=2
ly=(iiy-bottom-gapy*(npny-1))/float(npny)

lx0=lx*npnx+gapx*(npnx-1)
ix=iix; iy=iiy-ly

cm = plt.cm.get_cmap('nipy_spectral')
cm.set_bad('0.4')
cm.set_under('0.8')

lons_data=np.arange(lon0,360.1,dlon)
lats_data=np.arange(lat0,90.1,dlat)

clmin,clmax= int(sm_min)+1,int(sm_max)+1
clevels= np.linspace(clmin,clmax,51)

##-- Top Panel
ax1=fig.add_axes([ix,iy,lx0,ly],projection=ccrs.PlateCarree(central_longitude=180))  ### Now it's GeoAxes, not just Axes

subtit='(a) Global Mean'

props = dict(vmin=clmin,vmax=clmax,cmap=cm,alpha=0.9,transform=ccrs.PlateCarree())
cs=ax1.contourf(lons_data,lats_data,sstmean, clevels,**props)
#cs=ax1.pcolormesh(lons_data,lats_data,sstmean, **props)

map_common(ax1)

ax1.set_aspect('auto')

### Add colorbar
#- Get position from previous subplot
pos1 = ax1.get_position().bounds  ##<= (left,bottom,width,height)
cb_ax = fig.add_axes([pos1[0],pos1[1]-pos1[3]/6.,pos1[2],pos1[3]/15.])  ##<= (left,bottom,width,height)
cblab = "Temperature (\u00B0C)"
add_colorbar(cb_ax,cblab,horizontal=True)



##-- Bottom Panels

lons_data2=np.arange(lon_deg_range[0]+0.5,lon_deg_range[1],dlon)
lats_data2=np.arange(lat_deg_range[0]+0.5,lat_deg_range[1],dlat)

iy=iy-gapy-ly
ax2=fig.add_axes([ix,iy,lx,ly],
                 projection=ccrs.PlateCarree(central_longitude=-15))  ### Now it's GeoAxes, not just Axes 
ax2.set_extent([lon_deg_range[0]-10,lon_deg_range[1]+10,lat_deg_range[0]-5,lat_deg_range[1]+5],ccrs.PlateCarree())

subtit='(b) Masking All missings'

props = dict(vmin=clmin,vmax=clmax,cmap=cm,alpha=0.9,transform=ccrs.PlateCarree())
cs=ax2.pcolormesh(lons_data2,lats_data2,sstmean2, **props)

map_common(ax2,gl_loc=[True,False,False,True],gl_dlon=15,gl_dlat=10)

ax2.set_aspect('auto')

##-- Bottom Right
ix=ix+lx+gapx
ax3=fig.add_axes([ix,iy,lx,ly],
                 projection=ccrs.PlateCarree(central_longitude=-15))  ### Now it's GeoAxes, not just Axes 
ax3.set_extent([lon_deg_range[0]-10,lon_deg_range[1]+10,lat_deg_range[0]-5,lat_deg_range[1]+5],ccrs.PlateCarree())

subtit='(c) Using masked array'

props = dict(vmin=clmin,vmax=clmax,cmap=cm,alpha=0.9,transform=ccrs.PlateCarree())
cs=ax3.pcolormesh(lons_data2,lats_data2,sstmean_ma, **props)

map_common(ax3,gl_loc=[False,True,False,True],gl_dlon=15,gl_dlat=10)

#ax3.set_aspect('auto')

###--- Save Fig
#Change output directory and file name as wanted
outdir = "/discover/nobackup/jyoo8/py3_lecture_2019/Pics/"
fnout = "sst_map_myex1.png"

### Show or Save
plt.show()
#plt.savefig(outdir+fnout,bbox_inches='tight',dpi=175)
#plt.savefig(outdir+fnout,dpi=160)

if os.path.isfile(outdir+fnout) and not os.path.isfile('./Pics/'+fnout):
    call(["ln","-s",outdir+fnout,"./Pics/"])




NameError: name 'ccrs' is not defined

<Figure size 612x576 with 0 Axes>